# Generated by Django 4.2.9 on 2024-01-15 02:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IfcValidationRequest',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True, help_text='Timestamp this instance was created.')),
                ('updated', models.DateTimeField(help_text='Timestamp this instance was updated.', null=True)),
                ('id', models.AutoField(help_text='Identifier of the request (auto-generated).', primary_key=True, serialize=False)),
                ('file_name', models.CharField(help_text='Name of the file.', max_length=1024, verbose_name='file name')),
                ('file', models.FileField(help_text='Path of the file.', upload_to='')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('INITIATED', 'Initiated'), ('FAILED', 'Failed'), ('COMPLETED', 'Completed')], db_index=True, default='PENDING', help_text='Current status of the request.', max_length=10)),
                ('status_reason', models.TextField(blank=True, help_text='Reason for current status.', null=True)),
                ('created_by', models.ForeignKey(help_text='Who created this instance', on_delete=django.db.models.deletion.RESTRICT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(help_text='Who updated this instance.', null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'IFC Validation Request',
                'verbose_name_plural': 'IFC Validation Requests',
                'db_table': 'ifc_validation_request',
                'permissions': [('change_status', 'Can change status of IFC Validation Request')],
            },
        ),
        migrations.CreateModel(
            name='IfcValidationTask',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True, help_text='Timestamp this instance was created.')),
                ('updated', models.DateTimeField(help_text='Timestamp this instance was updated.', null=True)),
                ('id', models.AutoField(help_text='Identifier of the task (auto-generated).', primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('SYNTAX', 'STEP Physical File Syntax'), ('SCHEMA', 'IFC Schema (Express language)'), ('BSDD', 'Requirements per bSDD Classification'), ('INFO', 'Parse Info'), ('GHERKIN_BLOCKERS', 'Gherkin Rules - Blockers (TBC)'), ('GHERKIN_IA', 'Gherkin Rules - Implementer Agreements (IA)'), ('GHERKIN_IP', 'Gherkin Rules - Informal Propositions (IP)'), ('INDUSTRY', 'Industry Practices (TBC)')], db_index=True, help_text='Type of the task.', max_length=25)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SKIPPED', 'Skipped'), ('N/A', 'Not Applicable'), ('INITIATED', 'Initiated'), ('FAILED', 'Failed'), ('COMPLETED', 'Completed')], db_index=True, default='PENDING', help_text='Current status of the task.', max_length=15)),
                ('status_reason', models.TextField(blank=True, help_text='Reason for current status.', null=True)),
                ('started', models.DateTimeField(db_index=True, help_text='Timestamp the task was started.', null=True, verbose_name='started')),
                ('ended', models.DateTimeField(db_index=True, help_text='Timestamp the task was ended.', null=True, verbose_name='ended')),
                ('created_by', models.ForeignKey(help_text='Who created this instance', on_delete=django.db.models.deletion.RESTRICT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('request', models.ForeignKey(help_text='What IFC Validation Request this Task belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='ifc_validation_models.ifcvalidationrequest')),
                ('updated_by', models.ForeignKey(help_text='Who updated this instance.', null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'IFC Validation Task',
                'verbose_name_plural': 'IFC Validation Tasks',
                'db_table': 'ifc_validation_task',
            },
        ),
        migrations.AddIndex(
            model_name='ifcvalidationrequest',
            index=models.Index(fields=['file_name', 'status'], name='ifc_validat_file_na_442c43_idx'),
        ),
    ]
