# Generated by Django 5.1.3 on 2024-11-11 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ifc_validation_models', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='modelinstance',
            constraint=models.UniqueConstraint(fields=('model_id', 'stepfile_id', 'ifc_type'), name='modelid_stepfileid_ifctype'),
        ),
    ]
