# Generated by Django 5.1.3 on 2024-11-17 15:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ifc_validation_models', '0002_modelinstance_modelid_stepfileid_ifctype'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Version',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True, help_text='Timestamp this instance was created.')),
                ('updated', models.DateTimeField(blank=True, help_text='Timestamp this instance was last updated.', null=True)),
                ('id', models.AutoField(help_text='Identifier of the Version (auto-generated).', primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, help_text='Name of the Version, eg. 0.6.8', max_length=50, unique=True)),
                ('released', models.DateTimeField(help_text='Timestamp the Version was released.')),
                ('release_notes', models.TextField(blank=True, help_text='Description or URL of the Release Notes.', max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Version',
                'verbose_name_plural': 'Versions',
                'db_table': 'ifc_version',
            },
        ),
        migrations.CreateModel(
            name='UserAdditionalInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Timestamp this instance was created.')),
                ('updated', models.DateTimeField(blank=True, help_text='Timestamp this instance was last updated.', null=True)),
                ('is_vendor', models.BooleanField(blank=True, help_text='Whether this user belongs to an Authoring Tool vendor (optional)', null=True)),
                ('company', models.OneToOneField(blank=True, help_text='What Company the User belongs to (optional)', null=True, on_delete=django.db.models.deletion.CASCADE, to='ifc_validation_models.company')),
                ('created_by', models.ForeignKey(help_text='Who created this instance', on_delete=django.db.models.deletion.RESTRICT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, help_text='Who updated this instance.', null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(help_text='What User this additional info belongs to', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Additional Info',
                'verbose_name_plural': 'User Additional Info',
                'db_table': 'ifc_user_aditional_info',
            },
        ),
    ]
