# Generated by Django 5.1.3 on 2024-11-18 22:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ifc_validation_models', '0003_version_useradditionalinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useradditionalinfo',
            name='company',
            field=models.ForeignKey(blank=True, help_text='What Company the User belongs to (optional)', null=True, on_delete=django.db.models.deletion.CASCADE, to='ifc_validation_models.company'),
        ),
    ]
