# Generated by Django 5.1.3 on 2024-11-23 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ifc_validation_models', '0004_alter_useradditionalinfo_company_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='modelinstance',
            name='modelid_stepfileid_ifctype',
        ),
        migrations.AddConstraint(
            model_name='modelinstance',
            constraint=models.UniqueConstraint(fields=('model_id', 'stepfile_id'), name='modelid_stepfileid'),
        ),
    ]
