# Generated by Django 5.1.3 on 2025-01-02 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ifc_validation_models", "0005_update_modelinstance_constraint"),
    ]

    operations = [
        migrations.AddField(
            model_name="model",
            name="header_validation",
            field=models.JSONField(
                blank=True,
                help_text="Validation of the Header of the Model.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="model",
            name="status_header",
            field=models.CharField(
                choices=[
                    ("v", "Valid"),
                    ("i", "Invalid"),
                    ("n", "Not Validated"),
                    ("w", "Warning"),
                    ("-", "Not Applicable"),
                ],
                db_index=True,
                default="n",
                help_text="Status of the Header Validation.",
                max_length=1,
            ),
        ),
        migrations.AlterField(
            model_name="validationtask",
            name="type",
            field=models.CharField(
                choices=[
                    ("SYNTAX", "STEP Physical File Syntax"),
                    ("SCHEMA", "Schema (EXPRESS language)"),
                    ("MVD", "Model View Definitions"),
                    ("BSDD", "bSDD Compliance"),
                    ("INFO", "Parse Info"),
                    ("PREREQ", "Prerequisites"),
                    ("HEADER", "Header Validation"),
                    ("NORMATIVE_IA", "Implementer Agreements (IA)"),
                    ("NORMATIVE_IP", "Informal Propositions (IP)"),
                    ("INDUSTRY", "Industry Practices"),
                    ("INST_COMPLETION", "Instance Completion"),
                ],
                db_index=True,
                help_text="Type of the Validation Task.",
                max_length=25,
            ),
        ),
    ]
