# Generated by Django 5.1.6 on 2025-02-18 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ifc_validation_models', '0006_model_header_validation_model_status_header_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='useradditionalinfo',
            table='ifc_user_additional_info',
        ),
    ]
