# Generated by Django 5.1.6 on 2025-02-22 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ifc_validation_models', '0007_alter_useradditionalinfo_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='legal_name',
            field=models.CharField(blank=True, help_text='Legal name of the Company (optional).', max_length=1024, null=True),
        ),
    ]
