# Generated by Django 5.1.6 on 2025-02-22 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ifc_validation_models', '0008_company_legal_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='email_address_pattern',
            field=models.CharField(blank=True, help_text='Email address pattern(s) of the Company (optional).', max_length=1024, null=True, unique=True),
        ),
    ]
