# Generated by Django 5.1.6 on 2025-03-13 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ifc_validation_models', '0009_company_email_address_pattern'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='authoringtool',
            name='unique_name_version',
        ),
        migrations.AddConstraint(
            model_name='authoringtool',
            constraint=models.UniqueConstraint(fields=('name', 'version', 'company_id'), name='unique_name_version_company_id'),
        ),
        migrations.AddConstraint(
            model_name='authoringtool',
            constraint=models.UniqueConstraint(condition=models.Q(('company_id__isnull', True)), fields=('name', 'version'), name='unique_name_version_company_id_null'),
        ),
    ]
