# Generated by Django 5.1.6 on 2025-03-15 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ifc_validation_models', '0010_change_authoring_tool_unique_constraint'),
    ]

    operations = [
        migrations.AddField(
            model_name='useradditionalinfo',
            name='is_vendor_self_declared',
            field=models.BooleanField(blank=True, help_text='Whether this user has self-declared an affiliation with an Authoring Tool vendor (optional)', null=True),
        ),
    ]
