# Generated by Django 5.1.4 on 2025-06-19 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ifc_validation_models', '0013_model_status_signatures_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='model',
            name='status_syntax',
        ),
        migrations.AddField(
            model_name='model',
            name='status_syntax_data',
            field=models.CharField(choices=[('v', 'Valid'), ('i', 'Invalid'), ('n', 'Not Validated'), ('w', 'Warning'), ('-', 'Not Applicable')], db_index=True, default='n', help_text='Status of the Syntax Validation of the data section.', max_length=1),
        ),
        migrations.AddField(
            model_name='model',
            name='status_syntax_header',
            field=models.CharField(choices=[('v', 'Valid'), ('i', 'Invalid'), ('n', 'Not Validated'), ('w', 'Warning'), ('-', 'Not Applicable')], db_index=True, default='n', help_text='Status of the Syntax Validation of the header section.', max_length=1),
        ),
        migrations.AlterField(
            model_name='validationoutcome',
            name='outcome_code',
            field=models.CharField(choices=[('P00010', 'Passed'), ('N00010', 'Not Applicable'), ('E00001', 'Syntax Error'), ('E00011', 'Syntax Header Error'), ('E00012', 'Syntax Data Error'), ('E00002', 'Schema Error'), ('E00010', 'Type Error'), ('E00020', 'Value Error'), ('E00030', 'Geometry Error'), ('E00040', 'Cardinality Error'), ('E00050', 'Duplicate Error'), ('E00060', 'Placement Error'), ('E00070', 'Units Error'), ('E00080', 'Quantity Error'), ('E00090', 'Enumerated Value Error'), ('E00100', 'Relationship Error'), ('E00110', 'Naming Error'), ('E00120', 'Reference Error'), ('E00130', 'Resource Error'), ('E00140', 'Deprecation Error'), ('E00150', 'Shape Representation Error'), ('E00160', 'Instance Structure Error'), ('W00010', 'Alignment Contains Business Logic Only'), ('W00020', 'Alignment Contains Geometry Only'), ('W00030', 'Warning'), ('X00040', 'Executed')], default='N00010', help_text='Code representing the Validation Outcome.', max_length=10),
        ),
        migrations.AlterField(
            model_name='validationtask',
            name='type',
            field=models.CharField(choices=[('SYNTAX_HEADER', 'STEP Physical File Syntax (HEADER; section)'), ('SYNTAX_DATA', 'STEP Physical File Syntax (DATA; section)'), ('SCHEMA', 'Schema (EXPRESS language)'), ('MVD', 'Model View Definitions'), ('BSDD', 'bSDD Compliance'), ('INFO', 'Parse Info'), ('PREREQ', 'Prerequisites'), ('HEADER', 'Header Validation'), ('NORMATIVE_IA', 'Implementer Agreements (IA)'), ('NORMATIVE_IP', 'Informal Propositions (IP)'), ('INDUSTRY', 'Industry Practices'), ('INST_COMPLETION', 'Instance Completion'), ('DIGITAL_SIGNATURES', 'Digital Signatures')], db_index=True, help_text='Type of the Validation Task.', max_length=25),
        ),
    ]
