# Generated by Django 5.1.7 on 2025-07-23 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ifc_validation_models', '0014_model_status_header_syntax_alter_validationtask_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='validationrequest',
            name='channel',
            field=models.CharField(choices=[('WEBUI', 'WebUi'), ('API', 'Api')], db_index=True, default='WEBUI', help_text='What channel was used to create this Validation Request.', max_length=10),
        ),
    ]
