# Generated by Django 5.1.7 on 2025-07-23 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ifc_validation_models', '0015_validationrequest_channel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='validationrequest',
            name='channel',
            field=models.CharField(choices=[('WEBUI', 'WebUi'), ('API', 'Api')], db_index=True, default='API', help_text='What channel was used to create this Validation Request.', max_length=10),
        ),
    ]
