# Generated by Django 5.2.4 on 2025-11-08 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ifc_validation_models', '0017_add_user_ci_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='model',
            name='status_magic_clamav',
            field=models.CharField(choices=[('v', 'Valid'), ('i', 'Invalid'), ('n', 'Not Validated'), ('w', 'Warning'), ('-', 'Not Applicable')], db_index=True, default='n', help_text='Status of the file magic and anti-virus checks.', max_length=1),
        ),
        migrations.AlterField(
            model_name='validationtask',
            name='type',
            field=models.CharField(choices=[('MAGIC_AND_CLAMAV', 'File magic and anti-virus checks'), ('SYNTAX', 'STEP Physical File Syntax'), ('HEADER_SYNTAX', 'STEP Physical File Syntax (HEADER section)'), ('SCHEMA', 'Schema (EXPRESS language)'), ('MVD', 'Model View Definitions'), ('BSDD', 'bSDD Compliance'), ('INFO', 'Parse Info'), ('PREREQ', 'Prerequisites'), ('HEADER', 'Header Validation'), ('NORMATIVE_IA', 'Implementer Agreements (IA)'), ('NORMATIVE_IP', 'Informal Propositions (IP)'), ('INDUSTRY', 'Industry Practices'), ('INST_COMPLETION', 'Instance Completion'), ('DIGITAL_SIGNATURES', 'Digital Signatures')], db_index=True, help_text='Type of the Validation Task.', max_length=25),
        ),
    ]
