# Generated by Django 5.1.1 on 2025-10-08 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ifc_validation_models', '0017_add_user_ci_index'),
        ('ifc_validation_models', '0017_model_status_rocksdb_conversion_and_more'),
    ]

    operations = [
    ]
