# Generated by Django 5.2.8 on 2025-11-11 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ifc_validation_models', '0018_model_status_magic_clamav_alter_validationtask_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='validationrequest',
            name='file',
            field=models.FileField(help_text='Path of the file.', max_length=2048, upload_to=''),
        ),
    ]
