# Generated by Django 5.2.4 on 2025-12-29 21:10

import apps.ifc_validation_models.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ifc_validation_models', '0019_alter_validationrequest_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='validationrequest',
            name='status_reason',
            field=apps.ifc_validation_models.models.SanitizedCharField(blank=True, help_text='Reason for current status.', null=True),
        ),
        migrations.AlterField(
            model_name='validationtask',
            name='status_reason',
            field=apps.ifc_validation_models.models.SanitizedCharField(blank=True, help_text='Reason for current status.', null=True),
        ),
    ]
