# Generated by Django 5.1.1 on 2026-01-30 20:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ifc_validation_models', '0019_alter_validationrequest_file'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WhiteListEntry',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True, help_text='Timestamp this instance was created.')),
                ('updated', models.DateTimeField(blank=True, help_text='Timestamp this instance was last updated.', null=True)),
                ('id', models.AutoField(help_text='Identifier of the Whitelist Entry (auto-generated).', primary_key=True, serialize=False)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('created_by', models.ForeignKey(help_text='Who created this instance', on_delete=django.db.models.deletion.RESTRICT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, help_text='Who updated this instance.', null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WhiteListQueryFragment',
            fields=[
                ('id', models.AutoField(help_text='Identifier of the Query Fragment (auto-generated).', primary_key=True, serialize=False)),
                ('column', models.CharField(choices=[('instance__ifc_type', 'Instance type'), ('validation_task__type', 'Task type'), ('feature', 'Feature'), ('feature_version', 'Feature version'), ('expected', 'Expected'), ('observed', 'Observed')], help_text='Outcome column this query fragment is bound to', max_length=21)),
                ('operation', models.CharField(choices=[('EQUALS', 'Equals'), ('CONTAINS', 'Contains')], help_text='Predicate this query fragment is based on to', max_length=8)),
                ('right_hand_side', models.TextField(help_text='Right hand side of the query fragment', max_length=255)),
                ('whitelist_entry', models.ForeignKey(help_text='What Whitelist Entry this fragment is part of', on_delete=django.db.models.deletion.CASCADE, related_name='fragments', to='ifc_validation_models.whitelistentry')),
            ],
        ),
    ]
