# Generated by Django 5.2.4 on 2026-02-28 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ifc_validation_models', '0020_alter_validationrequest_status_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='validationrequest',
            name='file_removed',
            field=models.DateTimeField(db_index=True, help_text='Timestamp the file was removed.', null=True),
        ),
    ]
