# Generated by Django 5.1.1 on 2026-01-31 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ifc_validation_models', '0020_whitelistentry_whitelistqueryfragment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='whitelistqueryfragment',
            name='column',
            field=models.CharField(choices=[('instance__ifc_type', 'Instance type'), ('validation_task__type', 'Task type'), ('feature', 'Feature'), ('feature_version', 'Feature version'), ('expected', 'Expected'), ('observed', 'Observed'), ('validation_task__request__model__schema', 'Model schema')], help_text='Outcome column this query fragment is bound to', max_length=39),
        ),
    ]
