# Generated by Django 5.2.4 on 2026-02-21 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [
        (
            "ifc_validation_models",
            "0022_remove_validationoutcome_ifc_validat_feature_2540c6_idx_and_more",
        ),
        ("ifc_validation_models", "0023_alter_validationtask_type"),
    ]

    dependencies = [
        ("ifc_validation_models", "0021_alter_whitelistqueryfragment_column"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="validationoutcome",
            name="ifc_validat_feature_2540c6_idx",
        ),
        migrations.AlterField(
            model_name="validationoutcome",
            name="severity",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (1, "Executed"),
                    (2, "Passed"),
                    (3, "Warning"),
                    (4, "Error"),
                    (0, "N/A"),
                ],
                db_column="severity",
                db_index=True,
                default=0,
                help_text="Severity of the Validation Outcome.",
            ),
        ),
        migrations.RenameField(
            model_name="validationoutcome",
            old_name="severity",
            new_name="severity_in_db",
        ),
        migrations.AlterField(
            model_name="validationtask",
            name="type",
            field=models.CharField(
                choices=[
                    ("MAGIC_AND_CLAMAV", "File magic and anti-virus checks"),
                    ("SYNTAX", "STEP Physical File Syntax"),
                    ("HEADER_SYNTAX", "STEP Physical File Syntax (HEADER section)"),
                    ("SCHEMA", "Schema (EXPRESS language)"),
                    ("MVD", "Model View Definitions"),
                    ("BSDD", "bSDD Compliance"),
                    ("INFO", "Parse Info"),
                    ("PREREQ", "Prerequisites"),
                    ("HEADER", "Header Validation"),
                    ("NORMATIVE_IA", "Implementer Agreements (IA)"),
                    ("NORMATIVE_IP", "Informal Propositions (IP)"),
                    ("INDUSTRY", "Industry Practices"),
                    ("INST_COMPLETION", "Instance Completion"),
                    ("DIGITAL_SIGNATURES", "Digital Signatures"),
                    ("WHITELISTING", "Whitelisting"),
                ],
                db_index=True,
                help_text="Type of the Validation Task.",
                max_length=25,
            ),
        ),
        migrations.AddIndex(
            model_name="validationoutcome",
            index=models.Index(
                fields=["feature", "feature_version", "severity_in_db"],
                name="ifc_validat_feature_2540c6_idx",
            ),
        ),
        migrations.AlterField(
            model_name="validationtask",
            name="type",
            field=models.CharField(
                choices=[
                    ("MAGIC_AND_CLAMAV", "File magic and anti-virus checks"),
                    ("SYNTAX", "STEP Physical File Syntax"),
                    ("HEADER_SYNTAX", "STEP Physical File Syntax (HEADER section)"),
                    ("SCHEMA", "Schema (EXPRESS language)"),
                    ("MVD", "Model View Definitions"),
                    ("BSDD", "bSDD Compliance"),
                    ("INFO", "Parse Info"),
                    ("PREREQ", "Prerequisites"),
                    ("HEADER", "Header Validation"),
                    ("NORMATIVE_IA", "Implementer Agreements (IA)"),
                    ("NORMATIVE_IP", "Informal Propositions (IP)"),
                    ("INDUSTRY", "Industry Practices"),
                    ("INST_COMPLETION", "Instance Completion"),
                    ("DIGITAL_SIGNATURES", "Digital Signatures"),
                ],
                db_index=True,
                help_text="Type of the Validation Task.",
                max_length=25,
            ),
        ),
    ]
