# Generated by Django 5.2.4 on 2026-02-21 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "ifc_validation_models",
            "0022_remove_validationoutcome_ifc_validat_feature_2540c6_idx_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="validationtask",
            name="type",
            field=models.CharField(
                choices=[
                    ("MAGIC_AND_CLAMAV", "File magic and anti-virus checks"),
                    ("SYNTAX", "STEP Physical File Syntax"),
                    ("HEADER_SYNTAX", "STEP Physical File Syntax (HEADER section)"),
                    ("SCHEMA", "Schema (EXPRESS language)"),
                    ("MVD", "Model View Definitions"),
                    ("BSDD", "bSDD Compliance"),
                    ("INFO", "Parse Info"),
                    ("PREREQ", "Prerequisites"),
                    ("HEADER", "Header Validation"),
                    ("NORMATIVE_IA", "Implementer Agreements (IA)"),
                    ("NORMATIVE_IP", "Informal Propositions (IP)"),
                    ("INDUSTRY", "Industry Practices"),
                    ("INST_COMPLETION", "Instance Completion"),
                    ("DIGITAL_SIGNATURES", "Digital Signatures"),
                ],
                db_index=True,
                help_text="Type of the Validation Task.",
                max_length=25,
            ),
        ),
    ]
