# Generated by makemigration_whitelist on 2026-02-22T13:15:33.444607+00:00

from django.db import migrations


WHITELIST = [{'id': 1, 'description': 'IFC4 TransformerType Typographic error', 'fragments': [{'id': 1, 'column': 'validation_task__type', 'operation': 'EQUALS', 'right_hand_side': 'SCHEMA'}, {'id': 2, 'column': 'feature', 'operation': 'CONTAINS', 'right_hand_side': '"IfcTransformer.CorrectTypeAssigned"'}, {'id': 3, 'column': 'observed', 'operation': 'CONTAINS', 'right_hand_side': '=IfcTransformerType('}, {'id': 4, 'column': 'validation_task__request__model__schema', 'operation': 'EQUALS', 'right_hand_side': 'IFC4'}]}]


def forwards(apps, schema_editor):
    WhiteListEntry = apps.get_model("ifc_validation_models", "WhiteListEntry")
    WhiteListQueryFragment = apps.get_model("ifc_validation_models", "WhiteListQueryFragment")

    for e in WHITELIST:
        entry, _ = WhiteListEntry.objects.update_or_create(
            id=e["id"],
            defaults={"description": e["description"]},
        )
        for f in e["fragments"]:
            WhiteListQueryFragment.objects.update_or_create(
                id=f["id"],
                defaults={
                    "column": f["column"],
                    "operation": f["operation"],
                    "right_hand_side": f["right_hand_side"],
                    "whitelist_entry_id": entry.id,
                },
            )


def backwards(apps, schema_editor):
    WhiteListEntry = apps.get_model("ifc_validation_models", "WhiteListEntry")
    ids = [e["id"] for e in WHITELIST]
    WhiteListEntry.objects.filter(id__in=ids).delete()


class Migration(migrations.Migration):
    dependencies = [
        ("ifc_validation_models", "0022_remove_validationoutcome_ifc_validat_feature_2540c6_idx_and_more_squashed_0023_alter_validationtask_type"),
    ]

    operations = [
        migrations.RunPython(forwards, backwards),
    ]
