# Generated by Django 5.1.1 on 2026-02-22 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ifc_validation_models', '0022_remove_validationoutcome_ifc_validat_feature_2540c6_idx_and_more_squashed_0023_alter_validationtask_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='whitelistqueryfragment',
            name='column',
            field=models.CharField(choices=[('instance__ifc_type', 'Instance type'), ('validation_task__type', 'Task type'), ('feature', 'Feature'), ('feature_version', 'Feature version'), ('expected', 'Expected'), ('observed', 'Observed'), ('validation_task__request__model__schema', 'Model schema'), ('instance__fields', 'Instance fields')], help_text='Outcome column this query fragment is bound to', max_length=39),
        ),
    ]
