# Generated by makemigration_whitelist on 2026-02-24T09:17:41.191610+00:00

from django.db import migrations


WHITELIST = [{'id': 1, 'description': 'IFC4 TransformerType Typographic error', 'fragments': [{'id': 1, 'column': 'validation_task__type', 'operation': 'EQUALS', 'right_hand_side': 'SCHEMA'}, {'id': 2, 'column': 'feature', 'operation': 'CONTAINS', 'right_hand_side': '"IfcTransformer.CorrectTypeAssigned"'}, {'id': 3, 'column': 'observed', 'operation': 'CONTAINS', 'right_hand_side': '=IfcTransformerType('}, {'id': 4, 'column': 'validation_task__request__model__schema', 'operation': 'EQUALS', 'right_hand_side': 'IFC4'}]}, {'id': 2, 'description': 'IFC4 Qto_BuildingElementProxyQuantities quantity kinds', 'fragments': [{'id': 5, 'column': 'validation_task__type', 'operation': 'EQUALS', 'right_hand_side': 'NORMATIVE_IA'}, {'id': 6, 'column': 'feature', 'operation': 'EQUALS', 'right_hand_side': 'QTY001 - Standard quantities and quantity sets validation'}, {'id': 7, 'column': 'instance__fields', 'operation': 'CONTAINS', 'right_hand_side': '"Qto_BuildingElementProxyQuantities"'}, {'id': 8, 'column': 'expected', 'operation': 'CONTAINS', 'right_hand_side': '"IfcQuantityCount"'}, {'id': 14, 'column': 'validation_task__request__model__schema', 'operation': 'EQUALS', 'right_hand_side': 'IFC4'}]}, {'id': 3, 'description': 'IFC4 Qto_BuildingStoreyBaseQuantities quantity name', 'fragments': [{'id': 9, 'column': 'validation_task__type', 'operation': 'EQUALS', 'right_hand_side': 'NORMATIVE_IA'}, {'id': 10, 'column': 'feature', 'operation': 'EQUALS', 'right_hand_side': 'QTY001 - Standard quantities and quantity sets validation'}, {'id': 11, 'column': 'instance__fields', 'operation': 'CONTAINS', 'right_hand_side': '"Qto_BuildingStoreyBaseQuantities"'}, {'id': 12, 'column': 'observed', 'operation': 'CONTAINS', 'right_hand_side': '"NetHeight"'}, {'id': 13, 'column': 'validation_task__request__model__schema', 'operation': 'EQUALS', 'right_hand_side': 'IFC4'}]}]


def forwards(apps, schema_editor):
    WhiteListEntry = apps.get_model("ifc_validation_models", "WhiteListEntry")
    WhiteListQueryFragment = apps.get_model("ifc_validation_models", "WhiteListQueryFragment")

    for e in WHITELIST:
        entry, _ = WhiteListEntry.objects.update_or_create(
            id=e["id"],
            defaults={"description": e["description"]},
        )
        for f in e["fragments"]:
            WhiteListQueryFragment.objects.update_or_create(
                id=f["id"],
                defaults={
                    "column": f["column"],
                    "operation": f["operation"],
                    "right_hand_side": f["right_hand_side"],
                    "whitelist_entry_id": entry.id,
                },
            )


def backwards(apps, schema_editor):
    WhiteListEntry = apps.get_model("ifc_validation_models", "WhiteListEntry")
    ids = [e["id"] for e in WHITELIST]
    WhiteListEntry.objects.filter(id__in=ids).delete()


class Migration(migrations.Migration):
    dependencies = [
        ("ifc_validation_models", "0025_ifc4_transformertype_typographic_error_ifc4_qto_buildingelementproxyquantities_quantity_kinds"),
    ]

    operations = [
        migrations.RunPython(forwards, backwards),
    ]
