# Generated by Django 5.1.1 on 2026-03-10 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ifc_validation_models', '0021_validationrequest_file_removed'),
        ('ifc_validation_models', '0026_allowlist'),
    ]

    operations = [
    ]
