# Generated by Django 5.2.4 on 2026-04-12 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ifc_validation_models', '0027_merge_20260310_1043'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='whitelistentry',
            options={'verbose_name': 'Whitelist Entry', 'verbose_name_plural': 'Whitelist Entries'},
        ),
    ]
