from __future__ import annotations

from dataclasses import asdict, dataclass
from datetime import datetime, timezone
from pathlib import Path
import re
import sys

from django.apps import apps
from django.core.management.base import BaseCommand, CommandError


MIGRATION_TEMPLATE = """\
# Generated by {program} on {generated_at}

from django.db import migrations


WHITELIST = {payload}


def forwards(apps, schema_editor):
    WhiteListEntry = apps.get_model("{app_label}", "WhiteListEntry")
    WhiteListQueryFragment = apps.get_model("{app_label}", "WhiteListQueryFragment")

    for e in WHITELIST:
        entry, _ = WhiteListEntry.objects.update_or_create(
            id=e["id"],
            defaults={{"description": e["description"]}},
        )
        for f in e["fragments"]:
            WhiteListQueryFragment.objects.update_or_create(
                id=f["id"],
                defaults={{
                    "column": f["column"],
                    "operation": f["operation"],
                    "right_hand_side": f["right_hand_side"],
                    "whitelist_entry_id": entry.id,
                }},
            )


def backwards(apps, schema_editor):
    WhiteListEntry = apps.get_model("{app_label}", "WhiteListEntry")
    ids = [e["id"] for e in WHITELIST]
    WhiteListEntry.objects.filter(id__in=ids).delete()


class Migration(migrations.Migration):
    dependencies = [
        ("{app_label}", "{dependency}"),
    ]

    operations = [
        migrations.RunPython(forwards, backwards),
    ]
"""


class Command(BaseCommand):
    help = "Create a data migration that snapshots the current whitelist entries + fragments."

    def add_arguments(self, parser):
        parser.add_argument(
            "--app",
            default="ifc_validation_models",
            help="App label that contains WhiteListEntry/WhiteListQueryFragment.",
        )
        parser.add_argument(
            "--dry-run",
            action="store_true",
            help="Print migration contents instead of writing a file.",
        )

    def handle(self, *args, **opts):
        app_label: str = opts["app"]
        dry_run: bool = opts["dry_run"]

        try:
            app_config = apps.get_app_config(app_label)
        except LookupError as e:
            raise CommandError(str(e))

        from apps.ifc_validation_models.models import WhiteListEntry

        snaps = WhiteListEntry.get_all()

        payload = [asdict(d) for d in snaps]

        migrations_dir = Path(app_config.path) / "migrations"
        if not migrations_dir.exists():
            raise CommandError(f"Missing migrations dir: {migrations_dir}")

        number, dependency = self._latest_migration_name(migrations_dir)
        filename = f"{number + 1:04d}_allowlist.py"
        out_path = migrations_dir / filename

        content = MIGRATION_TEMPLATE.format(
            program=sys.argv[1],
            generated_at=datetime.now(timezone.utc).isoformat(),
            payload=repr(payload),
            app_label=app_label,
            dependency=dependency[:-3],
        )

        if dry_run:
            self.stdout.write(self.style.SUCCESS(f"Would create: {out_path}"))
            self.stdout.write(content)
            return

        out_path.write_text(content, encoding="utf-8")
        self.stdout.write(self.style.SUCCESS(f"Created migration: {out_path}"))

    def _latest_migration_name(self, migrations_dir: Path):
        def number_from_fn(p: Path):
            if m := re.match(r"^(?P<num>\d{4})_(?P<name>.+)\.py$", p.name):
                return int(m.group("num"))
            return -1
        return max((number_from_fn(p), p.name) for p in migrations_dir.iterdir())
